[[_spring_and_Polymer_js_a_secure_single_page_application]]
= A Secure Single Page Application

In this section we show some nice features of Spring Security, Spring Boot and Polymer working together to provide a pleasant and secure user experience. It should be accessible to beginners with Spring and Polymer, but there also is plenty of detail that will be of use to experts in either. This is actually the first in a series of sections on Spring Security and Polymer, with new features exposed in each one successively. We'll improve on the application in the <<_the_login_page_Polymer_js_and_spring_security_part_ii,second>> and subsequent installments, but the main changes after this are architectural rather than functional.

== Spring and the Single Page Application

HTML5, rich browser-based features, and the "single page application" are extremely valuable tools for modern developers, but any meaningful interactions will involve a backend server, so as well as static content (HTML, CSS and JavaScript) we are going to need a backend server. The backend server can play any or all of a number of roles: serving static content, sometimes (but not so often these days) rendering dynamic HTML, authenticating users, securing access to protected resources, and (last but not least) interacting with JavaScript in the browser through HTTP and JSON (sometimes referred to as a REST API).

Spring has always been a popular technology for building the backend features (especially in the enterprise), and with the advent of http://projects.spring.io/spring-boot[Spring Boot] things have never been easier. Let's have a look at how to build a new single page application from nothing using Spring Boot, Polymer and Twitter Bootstrap. There's no particular reason to choose that specific stack, but it is quite popular, especially with the core Spring constituency in enterprise Java shops, so it's a worthwhile starting point.

== Create a New Project

We are going to step through creating this application in some detail, so that anyone who isn't completely au fait with Spring and Polymer can follow what is happening. If you prefer to cut to the chase, you can link:#how-does-it-work[skip to the end] where the application is working, and see how it all fits together. There are various options for creating a new project:

* link:#using-curl[Using curl on the command line]
* link:#using-spring-boot-cli[Using Spring Boot CLI]
* link:#using-the-initializr-website[Using the Spring Initializr website]
* link:#using-spring-tool-suite[Using Spring Tool Suite]

The source code for the complete project we are going to build is in https://github.com/dsyer/spring-security-Polymer/tree/master/basic[Github here], so you can just clone the project and work directly from there if you want. Then jump to the link:#add-a-home-page[next section].

[[using-curl]]
=== Using Curl

The easiest way to create a new project to get started is via the https://start.spring.io[Spring Boot Initializr]. E.g. using curl on a UN*X like system:

[source]
----
$ mkdir ui && cd ui
$ curl https://start.spring.io/starter.tgz -d style=web \
-d style=security -d name=ui | tar -xzvf - 
----

You can then import that project (it's a normal Maven Java project by default) into your favourite IDE, or just work with the files and "mvn" on the command line. Then jump to the link:#add-a-home-page[next section].

[[using-spring-boot-cli]]
=== Using Spring Boot CLI

You can create the same project using the http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started-installing-the-cli[Spring Boot CLI], like this:

[source]
----
$ spring init --dependencies web,security ui/ && cd ui
----

Then jump to the link:#add-a-home-page[next section].

[[using-the-initializr-website]]
=== Using the Initializr Website

If you prefer you can also get the same code directly as a .zip file from the https://start.spring.io[Spring Boot Initializr]. Just open it up in your browser and select dependencies "Web" and "Security", then click on "Generate Project". The .zip file contains a standard Maven or Gradle project in the root directory, so you might want to create an empty directory before you unpack it. Then jump to the link:#add-a-home-page[next section].

[[using-spring-tool-suite]]
=== Using Spring Tool Suite

In http://spring.io/tools/sts[Spring Tool Suite] (a set of Eclipse plugins) you can also create and import a project using a wizard at `File-&gt;New-&gt;Spring Starter Project`. Then jump to the link:#add-a-home-page[next section].

[[add-a-home-page]]
== Add a Home Page

The core of a single page application is a static "index.html", so let's go ahead and create one (in "src/main/resources/static" or "src/main/resources/public"):

.index.html
[source,html]
----
<!doctype html>
<html>
<head>
<title>Can we use this!!! Huh !!! Huh!</title>
<script src="/js/bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
<link rel="import" href="/elements/theflies.html">
</head>
<body>
  <theflies></theflies>
</body>
</html>
----

It's pretty short and sweet because it is just going to say "Hello World".

=== Features of the Home Page

Salient features include:

* The polymer bootstrap js file (webcomponents-lite.min.js)
* The main module of polymer

We are going to create the script and stylesheet assets in a minute, but for now we can ignore the fact that they don't exist.

=== Running the Application

Once the home page file is added, your application will be loadable in a browser (even though it doesn't do much yet). On the command line you can do this

[source]
----
$ mvn spring-boot:run
----

and go to a browser at http://localhost:8080[http://localhost:8080]. When you load the home page you should get a browser dialog asking for username and password (the username is "user" and the password is printed in the console logs on startup). There's actually no content yet, so you should get a blank page with a "Greeting" header once you successfully authenticate.

TIP: If you don't like scraping the console log for the password just add this to the "application.properties" (in "src/main/resources"): `security.user.password=password` (and choose your own password). We did this in the sample code using "application.yml".

In an IDE, just run the `main()` method in the application class (there is only one class, and it is called `UiApplication` if you used the "curl" command above).

To package and run as a standalone JAR, you can do this:

[source]
----
$ mvn package
$ java -jar target/*.jar
----

== Front End Assets

For creating a Polymer project, we can reference at https://www.polymer-project.org/1.0/[Polymer] site. In our project, we going
to generate the core-module of our polymer project by concatenating several files from libraries.

We are going to use node, bower and gulp for building and generating our Polymer project.

== Update build.gradle node, bower and gulp

TBA

== Create the Polymer Application

Let's create the "the-flies" application (in "src/main/resources/static/resources/the-flies.html" so that the `&lt;link/&gt;` at the head of our "index.html" finds it in the right place to import).

A minimal Polymer application looks like this:

.the-flies.html
[source,html]
----
<link rel="import" href="./bower_components/polymer/polymer.html">
<link rel="import" href="./bower_components/iron-ajax/iron-ajax.html">
<link rel="import" href="./bower_components/paper-button/paper-button.html">

<dom-module id="the-flies">
    <style>
        div.bubble {
            margin: 20px;
            padding: 20px 20px;
            border-radius: 20px;
            background-color: #f1f1f1;
        }
    </style>

    <template>
        <iron-ajax id="dataService" url="/greeting" on-response="updateData"></iron-ajax>
        <div class="bubble">
            <h1>Greeting</h1>
            <div>
                <p>The ID is [[greeting.id]]</p>
                <p>The content is [[greeting.content]]</p>

                <paper-button on-click="getData">Get Server Data</paper-button>
            </div>
        </div>
    </template>
    <script>
        Polymer({
             is: "the-flies",
             properties: {
                greeting: {
                    type: Object,
                    value: {
                        "id": "ahihi",
                        "content": "welcome to my first training session"
                    }
                }
             },

             getData: function() {
                this.$.dataService.generateRequest();
             },
             updateData: function(evt) {
                this.greeting = evt.detail.response;
             }
        });
    </script>
</dom-module>
----

The name of the application is "the-flies"

_TBA: explain the source code of application_

[[dynamic-content]]
== Adding Dynamic Content

So far we have an application with a greeting that is hard coded. That's useful for learning how things fit together, but really we expect content to come from a backend server, so let's create an HTTP endpoint that we can use to grab a greeting. In your https://github.com/dsyer/spring-security-Polymer/blob/master/basic/src/main/java/demo/UiApplication.java[application class] (in "src/main/java/demo"), add the `@RestController` annotation and define a new `@RequestMapping`:

.Greeting.java
[source,java]
----
@RestController
public class Greeting {
    @GetMapping("/greeting")
    public Map<String, Object> greeting() {
        Map<String, Object> model = new HashMap<>(  );
        model.put( "id", UUID.randomUUID().toString() );
        model.put( "content", "okie baby! like thissssss! "+model.get("id") );

        return model;
    }
}
----

Run that application and try to curl the "/greeting" endpoint and you will find that it is secure by default:

[source]
----
$ curl localhost:8080/greeting
{"timestamp":1420442772928,"status":401,"error":"Unauthorized","message":"Full authentication is required to access this resource","path":"/resource"}
----

=== Loading a Dynamic Resource from Polymer
TBA

[[how-does-it-work]]
== How Does it Work?

The interactions between the browser and the backend can be seen in your browser if you use some developer tools (usually F12 opens this up, works in Chrome by default, may require a plugin in Firefox). Here's a summary:

|===
|Verb |Path |Status |Response

|GET |/ |401 |Browser prompts for authentication
|GET |/ |200 |index.html
|GET |/greeting |200 |JSON greeting
|===

You might not see the 401 because the browser treats the home page load as a single interaction, and you might see 2 requests for "/resource" because there is a http://en.wikipedia.org/wiki/Cross-origin_resource_sharing[CORS] negotiation.

Look more closely at the requests and you will see that all of them have an "Authorization" header, something like this:

[source]
----
Authorization: Basic dXNlcjpwYXNzd29yZA==
----

The browser is sending the username and password with every request (so remember to use HTTPS exclusively in production). There's nothing "Polymer" about that, so it works with your JavaScript framework or non-framework of choice.

=== What's Wrong with That?

On the face of it, it seems like we did a pretty good job, it's concise, easy to implement, all our data are secured by a secret password, and it would still work if we changed the front end or backend technologies. But there are some issues.

* Basic authentication is restricted to username and password authentication.

* The authentication UI is ubiquitous but ugly (browser dialog).

* There is no protection from http://en.wikipedia.org/wiki/Cross-site_request_forgery[Cross Site Request Forgery] (CSRF).

CSRF isn't really an issue with our application as it stands since it only needs to GET the backend resources (i.e. no state is changed in the server). As soon as you have a POST, PUT or DELETE in your application it simply isn't secure any more by any reasonable modern measure.

In the <<_the_login_page_Polymer_js_and_spring_security_part_ii,next section in this series>> we will extend the application to use form-based authentication, which is a lot more flexible than HTTP Basic. Once we have a form we will need CSRF protection, and both Spring Security and Polymer have some nice out-of-the box features to help with this. Spoiler: we are going to need to use the `HttpSession`.

****
Thanks: I would like to thank everyone who helped me develop this series, and in particular http://spring.io/team/rwinch[Rob Winch] and https://twitter.com/thspaeth[Thorsten Spaeth] for their careful reviews of the text and source code, and for teaching me a few tricks I didn't know even about the parts I thought I was most familar with.
****