debug: true

spring:
  aop:
    proxy-target-class: true

security:
  user.password: none
  ignored: /**/favicon.icon,/css/**,/resources/**,/images/**
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    logmeout:
      path: /logmeout/**
      url: http://localhost:9999/uaa/logout

logging.level:
  org.springframework.security: DEBUG
  com.tma.dc4b: DEBUG